Если метод exceptionDemo() в блоке try выбрасывает исключение, то блок catch обработывает его и выводит сообщение