Если метод exceptionDemo() в блоке try выбрасывает исключение, то блок catch обработывает его и выводит сообщение, а блок finally выводит сообщение в любом случае